name: Run Gather Script

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行（可选）
  push:
    branches: [ main, master ]  # 推送到主分支时触发
    paths:
      - 'Gather.bat'  # 当Gather.bat文件变更时触发

jobs:
  gather:
    runs-on: windows-latest  # 使用Windows运行器，因为要运行.bat文件
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run Gather.bat script
      run: |
        # 运行批处理脚本并捕获输出
        .\Gather.bat 2>&1 | Out-File -FilePath .\output.txt -Encoding UTF8
        
    - name: Create TV directory if not exists
      run: |
        if (!(Test-Path -Path "TV")) {
          New-Item -ItemType Directory -Path "TV" -Force
        }
        
    - name: Move output to TV directory
      run: |
        Move-Item -Path .\output.txt -Destination .\TV\Gather.txt -Force
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add TV/Gather.txt
        if (git diff --staged --quiet) {
          echo "No changes to commit"
        } else {
          git commit -m "Update Gather.txt from automated workflow"
          git push
        }
