name: 抓取内容并保存到仓库

on:
  schedule:
    - cron: '0 2 * * *'  # 可根据需要调整定时时间
  workflow_dispatch:

# 关键：添加权限配置，赋予 GITHUB_TOKEN 内容写入权限
permissions:
  contents: write  # 允许读写仓库内容（包括推送代码）
  actions: read    # 可选，仅读取 Actions 相关信息，最小权限原则

jobs:
  fetch-and-save:
    runs-on: windows-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        # 可选：若仓库是主分支（如 main），可添加 fetch-depth: 0 确保能提交
        with:
          fetch-depth: 0

      - name: 运行批处理抓取内容
        run: |
          .\fetch-content.bat
        shell: cmd

      - name: 提交并推送文件到仓库
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Gather.txt
          git diff --quiet --cached || (git commit -m "Auto update: Fetch latest content" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 此时已拥有 write 权限
