name: 抓取内容并保存到仓库

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  fetch-and-save:
    runs-on: windows-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史，避免提交冲突

      # 移除冗余的“切换目录”步骤：checkout 后默认已在 %GITHUB_WORKSPACE%（D:\a\AutoBuild\AutoBuild）
      # 直接打印当前目录确认，无需手动切换
      - name: 确认当前工作目录
        run: |
          echo 当前工作目录：%cd%  # 验证是否在仓库根目录
          dir  # 查看目录下是否有 fetch-content.bat（确认脚本存在）
        shell: cmd

      - name: 运行批处理抓取内容
        run: |
          .\fetch-content.bat  # 直接执行脚本（当前目录已正确）
        shell: cmd
        continue-on-error: false

      - name: 提交前验证文件状态
        run: |
          echo ============== 文件状态检查 ==============
          if exist "Gather.txt" (
              echo Gather.txt 存在
              dir Gather.txt  # 显示文件大小
              echo 文件前10行内容：
              head -n 10 Gather.txt
          ) else (
              echo 错误：Gather.txt 不存在！
              exit 1
          )
        shell: bash

      - name: 提交并推送文件到仓库
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Gather.txt
          if git diff --quiet --cached; then
              echo 无文件变更，无需提交
          else
              git commit -m "Auto update: Fetch latest content"
              git push
              echo 提交推送成功！
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
