name: huya
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 从指定链接下载huya
        run: |
          curl -f -o huya "http://123.56.43.183/tv/m3u/huya"
          echo "下载完成，文件大小：$(du -h huya)"

      - name: 检查m3u仓库是否存在
        id: check_repo
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token ${{ secrets.DAPANG }}" "https://api.github.com/repos/mr-pangpang/m3u")
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          echo "repo_exists=$([ "$HTTP_CODE" -eq 200 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: 若仓库不存在则创建
        if: steps.check_repo.outputs.repo_exists == 'false'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.DAPANG }}" \
          -H "Content-Type: application/json" \
          -d '{"name": "m3u", "auto_init": true}' \
          "https://api.github.com/user/repos"

      - name: 克隆m3u仓库
        run: |
          git clone https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git target-repo

      - name: 移动文件到目标路径
        run: |
          mv huya target-repo/
          echo "文件已移动到：target-repo/huya"

      - name: 提交并推送m3u仓库变更
        run: |
          cd target-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add huya
          CURRENT_TIME=$(date -d "+8 hours" +'%Y-%m-%d %H:%M:%S')
          git commit -m "updatetime $CURRENT_TIME" || echo "无文件变更，无需提交"
          git push https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git HEAD:main
