name: Keep Alive
on:
  schedule:
    # 每月1号凌晨2点自动保活
    - cron: "0 2 1 * *"
  workflow_dispatch: # 开启手动触发按钮

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予仓库写入权限，避免推送失败
    steps:
      - uses: actions/checkout@v4
      - name: 生成空提交保活仓库
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git commit --allow-empty -m "Auto keepalive commit 防止workflow被禁用"
          git push
