name: mr_migu_sports
on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 从指定链接下载migu_sports
        run: |
          curl -f -o migu_sports "https://raw.githubusercontent.com/YanG-1989/m3u/main/Migu.m3u"
          echo "下载完成，文件大小：$(du -h migu_sports)"
      # 新增：批量处理M3U文件内容（删除指定字段+修改group-title+删除括号内容）
      - name: 批量处理M3U文件内容
        run: |
          # 1. 删除所有包含 tvg-id="咪咕体育" 或 tvg-name="咪咕体育" 的内容（整段匹配删除）
          # 2. 将 group-title="•咪咕「移动」" 或 group-title="•咪咕「网·Ⅰ」" 统一改为 group-title="咪视界"
          # 3. 删除频道名称中的 「移动」「IPV4」 字符
          sed -i -E '
            /tvg-id="咪咕体育"|tvg-name="咪咕体育"/d;  # 删除含指定tvg字段的行
            s/group-title="•咪咕「(移动|网·Ⅰ)」"/group-title="咪视界"/g;  # 统一修改group-title
            s/「移动」//g; s/「IPV4」//g  # 删除频道名称中的目标字符
          ' migu_sports
          echo "文件内容处理完成，处理后前10行预览："
          head -10 migu_sports  # 预览处理结果（可选，可删除）
      - name: 检查m3u仓库是否存在
        id: check_repo
        run: |
          RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token ${{ secrets.DAPANG }}" "https://api.github.com/repos/mr-pangpang/m3u")
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          echo "repo_exists=$([ "$HTTP_CODE" -eq 200 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
      - name: 若仓库不存在则创建
        if: steps.check_repo.outputs.repo_exists == 'false'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.DAPANG }}" \
          -H "Content-Type: application/json" \
          -d '{"name": "m3u", "auto_init": false}' \
          "https://api.github.com/user/repos"
      - name: 克隆m3u仓库
        run: |
          git clone https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git target-repo
      - name: 移动处理后的文件到目标路径
        run: |
          mv migu_sports target-repo/
          echo "处理后的文件已移动到：target-repo/migu_sports"
      - name: 提交并推送m3u仓库变更
        run: |
          cd target-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add migu_sports
          CURRENT_TIME=$(date -d "+8 hours" +'%Y-%m-%d %H:%M:%S')  # 时区调整（+8小时为北京时间）
          git commit -m "updatetime $CURRENT_TIME (processed M3U content)" || echo "无文件变更，无需提交"  # 提交信息增加“处理标记”
          git push https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git HEAD:main
