name: mr_migu_sports
on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 从指定链接下载migu_sports（替换为你的实际M3U链接，避免404）
        run: |
          # 注意：如果原链接失效，替换成你能正常访问的M3U文件链接（如直链/仓库链接）
          curl -f -o migu_sports "https://raw.githubusercontent.com/YanG-1989/m3u/main/Migu.m3u" || { echo "下载失败，检查链接有效性"; exit 1; }
          echo "下载完成，原文件行数：$(wc -l migu_sports) 行"  # 显示原文件行数，确认没下空
      # 修复核心：精准处理（只删指定字段+改group-title+清特殊字符，不删整行）
      - name: 精准处理M3U文件内容（避免删空）
        run: |
          sed -i -E '
            # 1. 只删除 "tvg-id=\"咪咕体育\" " 或 "tvg-name=\"咪咕体育\" "（末尾空格保留，避免字段粘连）
            s/tvg-id="咪咕体育" //g;
            s/tvg-name="咪咕体育" //g;
            # 2. 统一修改group-title为"咪视界"
            s/group-title="•咪咕「(移动|网·Ⅰ)」"/group-title="咪视界"/g;
            # 3. 删除频道名中的「移动」「IPV4」
            s/「移动」//g;
            s/「IPV4」//g
          ' migu_sports
          
          # 验证处理结果：显示处理后的行数和前5行，确认内容非空
          echo "处理后文件行数：$(wc -l migu_sports) 行"
          echo "处理后内容预览（前5行）："
          head -5 migu_sports
      - name: 检查目标仓库并克隆（同前，确保仓库可访问）
        run: |
          if ! git clone https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git target-repo; then
            echo "克隆失败，检查token权限或仓库地址"
            exit 1
          fi
      - name: 移动并推送处理后的文件
        run: |
          mv migu_sports target-repo/
          cd target-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add migu_sports
          CURRENT_TIME=$(date -d "+8 hours" +'%Y-%m-%d %H:%M:%S')
          git commit -m "updatetime $CURRENT_TIME (fixed empty content)" || echo "无变更无需提交"
          git push || echo "推送失败，检查token权限"
