name: mr_migu_sports
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  process-m3u-safely:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取基础代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 下载文件
        run: |
          curl -f -o original_migu.m3u "https://raw.githubusercontent.com/YanG-1989/m3u/main/Migu.m3u" || { echo "链接失效！换能访问的M3U链接"; exit 1; }
          echo "原始文件总行数：$(wc -l original_migu.m3u) 行"

      - name: 处理文件
        run: |
          awk '/^#EXTINF:-1/ { print $0; getline; if ($0 ~ /^http.*\.m3u8/) print $0 }' original_migu.m3u > temp_processed.m3u
          sed -i -E '
            s/tvg-id="咪咕体育" //g;
            s/tvg-name="咪咕体育" //g;
            s/group-title="•咪咕「(移动|网·Ⅰ)」"/group-title="咪视界"/g;
            s/「移动」//g;
            s/「IPV4」//g;
            s/  +/ /g
          ' temp_processed.m3u
          mv temp_processed.m3u migu_sports
          echo "处理后文件总行数：$(wc -l migu_sports) 行"
          echo "处理后包含的m3u8链接数量：$(grep -c "\.m3u8" migu_sports) 个"

      - name: 推送处理后的文件
        run: |
          if ! git clone https://${{ secrets.DAPANG }}@github.com/mr-pangpang/m3u.git target-repo; then
            echo "仓库克隆失败！检查token权限/仓库地址"
            exit 1
          fi
          mv migu_sports target-repo/
          cd target-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add migu_sports
          git commit -m "updatetime $(date +'%Y%m%d_%H%M')" || echo "无新变更，无需提交"
          git push || echo "推送失败！检查token是否有push权限"
