name: Run Gather Script

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'script/Gather.bat'

jobs:
  gather:
    runs-on: windows-latest
    
    # 关键：给工作流写入权限
    permissions:
      contents: write
    
    steps:
    - name: Checkout with token
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用GITHUB_TOKEN进行认证
        
    - name: Run script and create output
      run: |
        if not exist TV mkdir TV
        cd script
        call Gather.bat > ..\TV\Gather.txt 2>&1
      shell: cmd
      
    - name: Setup Git identity
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      
    - name: Push changes
      run: |
        git add TV/Gather.txt
        # 检查是否有变化，避免空提交
        if not git diff --cached --quiet; then
          git commit -m "Auto-update Gather.txt"
          git push
        else
          echo "No changes to commit"
        fi
      shell: cmd
