name: tv-file-merge-process-sync
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  download-merge-clean-save-tv:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 下载 tv 源文件
        run: |
          curl -f -o tv_source "http://123.56.43.183/tv/m3u/tv"
          echo "tv 源文件下载完成，大小：$(du -h tv_source)"
      - name: 下载 migu_video 源文件
        run: |
          curl -f -o migu_source "https://raw.githubusercontent.com/develop202/migu_video/refs/heads/main/interface.txt"
          echo "migu_video 源文件下载完成，大小：$(du -h migu_source)"
      - name: 合并两个源文件
        run: |
          cat tv_source migu_source > tv_temp
          echo "源文件合并完成，临时文件大小：$(du -h tv_temp)"
      - name: 清理步骤1 - 删除 svg-id 和 svg-name 字段
        run: |
          sed -i -E 's/(svg-id=("([^"]*)"|'\''([^'\'']*)'\''))[[:space:]]*(svg-name=("([^"]*)"|'\''([^'\'']*)'\''))//g' tv_temp
          sed -i -E 's/(svg-id=("([^"]*)"|'\''([^'\'']*)'\''))//g' tv_temp
          sed -i -E 's/(svg-name=("([^"]*)"|'\''([^'\'']*)'\''))//g' tv_temp
          echo "已删除所有 svg-id 和 svg-name 字段"
      - name: 清理步骤2 - 删除 tvg-id 字段
        run: |
          sed -i -E 's/(tvg-id=("([^"]*)"|'\''([^'\'']*)'\''))//g' tv_temp
          echo "已删除所有 tvg-id 字段"
      - name: 清理步骤3 - 删除 tvg-name 字段
        run: |
          sed -i -E 's/(tvg-name=("([^"]*)"|'\''([^'\'']*)'\''))//g' tv_temp
          echo "已删除所有 tvg-name 字段"
      - name: 清理步骤4 - 优化文本格式
        run: |
          sed -i -e 's/  */ /g' -e 's/^ //' -e 's/ $//' -e '/^$/d' tv_temp
          mv tv_temp tv
